-- 0009 — the driver list for the remaining leaves.
--
-- Every row here ENCODES docs/INDUSTRY-INTELLIGENCE.md §3, which the owner
-- already wrote: the 领先 / 同步 / 滞后 lists per industry. Nothing is
-- invented — where §3 states no elasticity, the band stays NULL rather than
-- being filled with a plausible number, because a fabricated magnitude is
-- exactly what convention #1 forbids and what §5's backtest would later
-- "confirm" against nothing.
--
-- None of these have a series yet. That is the point of storing them: each
-- row names the feed it needs in `source_name`, so this table doubles as the
-- data shopping list. `GET /v1/industries/:id/drivers` reports them as
-- untested and says why, which is the honest form of a to-do.
--
-- Placement follows the splitting rule: drivers hang off the leaf whose
-- drivers they are. DRAM and NAND carry the capacity-cycle model, HBM carries
-- the supply-bound model, and the two foundry nodes carry different leading
-- indicators — which is why those splits exist at all.

INSERT INTO industry_driver (
  industry_id, key, name, name_zh, what_it_is, phase, lag_quarters, affects,
  direction, target_metric, who_it_hits, series_key, frequency, kind,
  confidence, source_name, source_url
) VALUES
  -- ── DRAM / NAND — a CAPACITY-CYCLE model ─────────────────────────────────
  -- Not a spread model: the dominant cost is depreciation on a multi-billion
  -- dollar fab, so watching input prices tells you almost nothing.
  ('memory-dram', 'inventory_weeks', 'Channel inventory weeks', '渠道库存周数',
   '客户手上的库存周数。★ 这条是整个存储周期最早的信号：库存拐点先出现，合约价与毛利率随后。',
   'leading', 2, 'Pricing', -1, 'gross_margin_pct',
   '所有存储厂；杠杆高、产品单一的厂受伤最快。',
   NULL, 'monthly', 'assumption', 0.3,
   'TrendForce / DRAMeXchange (paid — out of scope per HANDOFF §13.10) or filings commentary', NULL),
  ('memory-dram', 'maker_capex', 'Top-three maker capex', '三大厂资本开支',
   '三星、SK hynix、Micron 的资本开支合计。今天的 capex 就是 4–6 季后的供给。',
   'leading', 5, 'Supply', -1, 'gross_margin_pct',
   '全行业 —— 供给是共有的，谁都躲不掉。',
   NULL, 'quarterly', 'assumption', 0.3,
   'SEC/DART filings (derivable from ingested financials — not yet extracted)', NULL),
  ('memory-dram', 'spot_contract_spread', 'Spot vs contract spread', '现货与合约价差',
   '现货相对合约价的溢价/折价，是合约价下一次调整方向的领先指标。',
   'leading', 1, 'Pricing', 1, 'gross_margin_pct',
   '现货敞口大的厂更早反映。',
   NULL, 'weekly', 'assumption', 0.3,
   'TrendForce / DRAMeXchange (paid — out of scope)', NULL),
  ('memory-dram', 'contract_price', 'DRAM contract price', 'DRAM 合约价',
   '月底议定的合约价。价格是滞后确认：等合约价转涨时，存储股往往已经走了 6–9 个月。',
   'coincident', 0, 'Revenue', 1, 'gross_margin_pct',
   '全行业。',
   NULL, 'monthly', 'assumption', 0.3,
   'TrendForce / DRAMeXchange (paid — out of scope)', NULL),
  ('memory-dram', 'bit_shipment_growth', 'Bit shipment growth', '位元出货增速',
   '出货位元的同比增速，需求侧的同步读数。',
   'coincident', 0, 'Volume', 1, 'gross_margin_pct',
   '全行业。',
   NULL, 'quarterly', 'assumption', 0.3,
   'WSTS / company filings (not yet ingested)', NULL),

  ('memory-nand', 'inventory_weeks', 'Channel inventory weeks', '渠道库存周数',
   'NAND 渠道库存周数 —— 与 DRAM 同为周期最早信号，但终端结构不同（企业级 SSD vs 手机）。',
   'leading', 2, 'Pricing', -1, 'gross_margin_pct',
   '所有 NAND 厂。',
   NULL, 'monthly', 'assumption', 0.3,
   'TrendForce (paid — out of scope)', NULL),
  ('memory-nand', 'maker_capex', 'Maker capex', '厂商资本开支',
   'NAND 厂商资本开支；层数迁移使单位产能投资与 DRAM 不同步。',
   'leading', 5, 'Supply', -1, 'gross_margin_pct',
   '全行业。',
   NULL, 'quarterly', 'assumption', 0.3,
   'Filings (derivable from ingested financials — not yet extracted)', NULL),
  ('memory-nand', 'contract_price', 'NAND contract price', 'NAND 合约价',
   'NAND 合约价，滞后确认。',
   'coincident', 0, 'Revenue', 1, 'gross_margin_pct',
   '全行业。',
   NULL, 'monthly', 'assumption', 0.3,
   'TrendForce (paid — out of scope)', NULL),

  -- ── HBM — a SUPPLY-BOUND model ───────────────────────────────────────────
  -- Demand is not the question; allocation is.
  ('memory-hbm', 'cowos_capacity', 'CoWoS packaging capacity', 'CoWoS 封装产能',
   '★ HBM 出得了多少，取决于台积电 CoWoS 封装产能，而不是 HBM 产线本身。这是全链条最硬的瓶颈。',
   'leading', 1, 'Volume', 1, 'gross_margin_pct',
   '拿到分配的厂受益；分配是排他的。',
   NULL, 'quarterly', 'assumption', 0.3,
   'TSMC filings/commentary + supply-chain press (not yet ingested)', NULL),
  ('memory-hbm', 'gpu_shipments', 'AI GPU shipments', 'AI GPU 出货量',
   'HBM 的唯一大客户就是 AI 加速器；GPU 出货即 HBM 需求。',
   'leading', 1, 'Volume', 1, 'gross_margin_pct',
   '全行业。',
   NULL, 'quarterly', 'assumption', 0.3,
   'Company filings / supply-chain estimates (not yet ingested)', NULL),
  ('memory-hbm', 'hbm_price', 'HBM unit price', 'HBM 单价',
   'HBM 单价，同步读数。供给受限时价格坚挺。',
   'coincident', 0, 'Revenue', 1, 'gross_margin_pct',
   '全行业。',
   NULL, 'quarterly', 'assumption', 0.3,
   'TrendForce (paid — out of scope)', NULL),
  ('memory-hbm', 'yield', 'HBM stacking yield', 'HBM 堆叠良率',
   '堆叠良率直接决定有效产能与单位成本 —— 良率差距是各厂盈利差距的主因。',
   'coincident', 0, 'COGS', 1, 'gross_margin_pct',
   '良率落后的厂被双重打击：可售量少、单位成本高。',
   NULL, 'quarterly', 'assumption', 0.3,
   'Company commentary (not quantitatively disclosed — may never be a series)', NULL),

  -- ── Foundry: advanced follows customer capex, mature follows autos ───────
  ('foundry-advanced', 'customer_capex', 'Customer capex & orders', '客户资本开支与订单',
   '先进制程的需求就是大客户的 capex 与下单节奏。',
   'leading', 2, 'Volume', 1, 'gross_margin_pct',
   '先进制程占比高的厂。',
   NULL, 'quarterly', 'assumption', 0.3,
   'Hyperscaler + fabless filings (derivable from ingested financials — not yet extracted)', NULL),
  ('foundry-advanced', 'new_fab_timeline', 'New fab ramp timeline', '新厂投产时程',
   '新厂投产会在 4–6 季后变成供给。产能来得比需求快，定价权就转移。',
   'leading', 5, 'Pricing', -1, 'gross_margin_pct',
   '全行业；后发厂尤甚。',
   NULL, 'quarterly', 'assumption', 0.3,
   'Company announcements (not yet ingested)', NULL),
  ('foundry-advanced', 'utilisation', 'Capacity utilisation', '产能利用率',
   '★ 代工是重资产生意，利用率直接决定折旧摊薄，是毛利率的同步主因。',
   'coincident', 0, 'COGS', 1, 'gross_margin_pct',
   '折旧负担最重的厂杠杆最大。',
   NULL, 'quarterly', 'assumption', 0.3,
   'Company filings (not yet ingested)', NULL),
  ('foundry-mature', 'auto_industrial_inventory', 'Auto & industrial inventory', '汽车/工业库存',
   '成熟制程跟的是汽车与工业客户的库存，不是 AI。两条周期经常反相。',
   'leading', 2, 'Volume', -1, 'gross_margin_pct',
   '成熟制程占比高的厂。',
   NULL, 'monthly', 'assumption', 0.3,
   'FRED (auto/industrial inventories — needs FRED_API_KEY)', 'https://fred.stlouisfed.org/'),
  ('foundry-mature', 'utilisation', 'Capacity utilisation', '产能利用率',
   '同上：利用率决定折旧摊薄。成熟制程的利用率波动更贴近工业周期。',
   'coincident', 0, 'COGS', 1, 'gross_margin_pct',
   '全行业。',
   NULL, 'quarterly', 'assumption', 0.3,
   'Company filings (not yet ingested)', NULL),

  -- ── Equipment — the earliest signal in the whole chain ────────────────────
  ('semis-equipment', 'book_to_bill', 'Book-to-bill ratio', '订单出货比 (B/B)',
   '★ 设备订单出货比。整条链上最早的信号：设备先于代工，代工先于芯片，芯片先于终端。',
   'leading', 2, 'Revenue', 1, 'gross_margin_pct',
   '全行业。',
   NULL, 'monthly', 'assumption', 0.3,
   'SEMI billings report (not free — check licence)', NULL),
  ('semis-equipment', 'fab_capex', 'Fab capex announcements', '晶圆厂资本开支公告',
   '设备营收滞后晶圆厂 capex 约 2–3 季 —— 公告即订单，订单即两三个季度后的收入。',
   'leading', 3, 'Revenue', 1, 'gross_margin_pct',
   '前道设备厂最直接；后道滞后更久。',
   NULL, 'quarterly', 'assumption', 0.3,
   'Foundry/IDM filings (derivable from ingested financials — not yet extracted)', NULL),

  -- ── AI accelerators — supply-constrained, so watch supply ────────────────
  ('semis-accelerators', 'cowos_capacity', 'CoWoS packaging capacity', 'CoWoS 封装产能',
   '★ 需求不是问题，供给才是。盯需求会看错边 —— 出货量的上限是封装产能。',
   'leading', 1, 'Volume', 1, 'gross_margin_pct',
   '拿到分配的厂受益。',
   NULL, 'quarterly', 'assumption', 0.3,
   'TSMC commentary + supply-chain press (not yet ingested)', NULL),
  ('semis-accelerators', 'hbm_supply', 'HBM supply', 'HBM 供给',
   '每颗加速器都要配 HBM；HBM 供不上，加速器就出不了货。',
   'leading', 1, 'Volume', 1, 'gross_margin_pct',
   '全行业。',
   NULL, 'quarterly', 'assumption', 0.3,
   'Memory maker filings/commentary (not yet ingested)', NULL),
  ('semis-accelerators', 'hyperscaler_capex', 'Hyperscaler capex guidance', '超大厂资本开支指引',
   '超大规模云厂的 capex 指引，是需求侧最可信的前瞻数字（他们自己公布）。',
   'leading', 2, 'Volume', 1, 'gross_margin_pct',
   '全行业。',
   NULL, 'quarterly', 'assumption', 0.3,
   'Hyperscaler filings (MSFT/GOOGL/AMZN/META — not in coverage universe yet)', NULL),

  -- ── Networking / ASIC ────────────────────────────────────────────────────
  ('networking', 'datacenter_capex', 'Data-centre capex', '数据中心资本开支',
   '网络设备的需求直接来自数据中心建设支出。',
   'leading', 2, 'Revenue', 1, 'gross_margin_pct',
   '全行业。',
   NULL, 'quarterly', 'assumption', 0.3,
   'Hyperscaler filings (not in coverage universe yet)', NULL),
  ('networking', 'port_speed_migration', 'Port speed migration', '端口速率迁移',
   '400G → 800G → 1.6T 的迁移节奏。每一次迁移都是一轮换机需求，也是一次份额重排。',
   'leading', 4, 'Revenue', 1, 'gross_margin_pct',
   '在新速率上先量产的厂吃到溢价。',
   NULL, 'quarterly', 'assumption', 0.3,
   'Industry reports / company commentary (not yet ingested)', NULL),

  -- ── Data-centre power & cooling ──────────────────────────────────────────
  ('dc-power-cooling', 'new_capacity_mw', 'New data-centre capacity (MW)', '新增装机容量 (MW)',
   '★ 新增装机容量是这门生意的需求本体 —— 每一兆瓦都要配电与散热。',
   'leading', 2, 'Revenue', 1, 'gross_margin_pct',
   '全行业。',
   NULL, 'quarterly', 'assumption', 0.3,
   'Industry trackers / hyperscaler disclosures (not yet ingested)', NULL),
  ('dc-power-cooling', 'backlog_ratio', 'Backlog to revenue', '订单积压/营收比',
   '订单积压相对营收的倍数，反映未来几季的收入能见度。',
   'leading', 1, 'Revenue', 1, 'gross_margin_pct',
   '全行业。',
   NULL, 'quarterly', 'assumption', 0.3,
   'Company filings (not yet extracted)', NULL),
  ('dc-power-cooling', 'copper_price', 'Copper price', '铜价',
   '铜是配电设备的主要原料成本。',
   'coincident', 0, 'COGS', -1, 'gross_margin_pct',
   '低压配电、母线槽等铜含量高的产品线受伤更大。',
   NULL, 'daily', 'assumption', 0.3,
   'FRED (PCOPPUSDM — needs FRED_API_KEY)', 'https://fred.stlouisfed.org/series/PCOPPUSDM'),
  ('dc-power-cooling', 'electricity_price', 'Electricity price', '电价',
   '电价越高，数据中心越愿意为能效付钱 —— 对散热与配电厂商是需求驱动，不是成本。',
   'coincident', 0, 'Volume', 1, 'gross_margin_pct',
   '高能效产品线占比高的厂受益更多。',
   NULL, 'monthly', 'assumption', 0.3,
   'EIA (needs EIA_API_KEY)', 'https://www.eia.gov/opendata/')
ON CONFLICT (industry_id, key) DO UPDATE SET
  name = EXCLUDED.name,
  name_zh = EXCLUDED.name_zh,
  what_it_is = EXCLUDED.what_it_is,
  phase = EXCLUDED.phase,
  lag_quarters = EXCLUDED.lag_quarters,
  affects = EXCLUDED.affects,
  direction = EXCLUDED.direction,
  target_metric = EXCLUDED.target_metric,
  who_it_hits = EXCLUDED.who_it_hits,
  frequency = EXCLUDED.frequency,
  source_name = EXCLUDED.source_name,
  source_url = EXCLUDED.source_url;
