/**
 * Generates edgar-seed.sql from facts.json (offline, deterministic — CI-safe).
 *
 * Upserts use natural keys, never INSERT OR REPLACE:
 *   - financial_period ON CONFLICT(company_id, period_label): period keeps
 *     its id (facts referencing it survive); source pointer moves to EDGAR.
 *   - financial_fact inserts SELECT the period id by natural key, and
 *     ON CONFLICT(period_id, concept) update value + source — EDGAR wins
 *     where it maps a concept, manual-seed facts it doesn't map survive.
 *
 * Run:
 *   node seed/edgar/generate.mjs
 *   wrangler d1 execute atlas-db --local --file=seed/edgar/edgar-seed.sql
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const { provenance, companies } = JSON.parse(
  readFileSync(join(here, "facts.json"), "utf8"),
);

const q = (s) =>
  s === null || s === undefined ? "NULL" : `'${String(s).replace(/'/g, "''")}'`;
const n = (v) => (v === null || v === undefined ? "NULL" : String(v));

const retrievedAt = /retrieved (\d{4}-\d{2}-\d{2})/.exec(provenance)?.[1] ?? null;

const lines = [];
lines.push("-- Generated by seed/edgar/generate.mjs — do not edit by hand.");
// (Postgres/Supabase — no PRAGMA; upserts use natural-key ON CONFLICT.)

let periodCount = 0;
let quarterCount = 0;
let factCount = 0;

for (const c of companies) {
  const sourceId = `sec-edgar-${c.id}`;
  lines.push(
    `INSERT INTO source (id, kind, name, url, retrieved_at, note) VALUES (` +
      [
        q(sourceId),
        q("sec-edgar"),
        q(`SEC EDGAR companyfacts — ${c.entityName}`),
        q(c.url),
        q(retrievedAt),
        q(provenance),
      ].join(", ") +
      `) ON CONFLICT(id) DO UPDATE SET retrieved_at=excluded.retrieved_at, note=excluded.note;`,
  );

  for (const fy of Object.keys(c.years).sort()) {
    const label = `FY${String(fy).slice(2)}`;
    const facts = c.years[fy];
    lines.push(
      `INSERT INTO financial_period (company_id, period_label, period_type, fiscal_year, fiscal_quarter, currency, unit, source_id) VALUES (` +
        [q(c.id), q(label), q("annual"), n(fy), "NULL", q("USD"), q("USD millions"), q(sourceId)].join(", ") +
        `) ON CONFLICT(company_id, period_label) DO UPDATE SET source_id=excluded.source_id, fiscal_year=excluded.fiscal_year;`,
    );
    periodCount += 1;
    for (const [concept, value] of Object.entries(facts)) {
      lines.push(
        `INSERT INTO financial_fact (period_id, concept, value, source_id) ` +
          `SELECT id, ${q(concept)}, ${n(value)}, ${q(sourceId)} FROM financial_period ` +
          `WHERE company_id=${q(c.id)} AND period_label=${q(label)} ` +
          `ON CONFLICT(period_id, concept) DO UPDATE SET value=excluded.value, source_id=excluded.source_id;`,
      );
      factCount += 1;
    }
  }

  /*
   * Quarterly periods (P022 v2). Same upsert shape as annual — the natural key
   * is (company_id, period_label) — but `period_type` is 'quarter' and
   * `fiscal_quarter` is set, which is what the /financials Quarterly tab and
   * the quarter-over-quarter charts filter on.
   *
   * Keys arrive as "2026Q3" from quarters.mjs and render as "Q3 FY26".
   */
  for (const key of Object.keys(c.quarters ?? {}).sort()) {
    const [fyStr, qtrStr] = key.split("Q");
    const fy = Number(fyStr);
    const qtr = Number(qtrStr);
    const label = `Q${qtr} FY${String(fy).slice(2)}`;
    const facts = c.quarters[key];
    lines.push(
      `INSERT INTO financial_period (company_id, period_label, period_type, fiscal_year, fiscal_quarter, currency, unit, source_id) VALUES (` +
        [q(c.id), q(label), q("quarter"), n(fy), n(qtr), q("USD"), q("USD millions"), q(sourceId)].join(", ") +
        `) ON CONFLICT(company_id, period_label) DO UPDATE SET source_id=excluded.source_id, fiscal_year=excluded.fiscal_year, fiscal_quarter=excluded.fiscal_quarter;`,
    );
    quarterCount += 1;
    for (const [concept, value] of Object.entries(facts)) {
      lines.push(
        `INSERT INTO financial_fact (period_id, concept, value, source_id) ` +
          `SELECT id, ${q(concept)}, ${n(value)}, ${q(sourceId)} FROM financial_period ` +
          `WHERE company_id=${q(c.id)} AND period_label=${q(label)} ` +
          `ON CONFLICT(period_id, concept) DO UPDATE SET value=excluded.value, source_id=excluded.source_id;`,
      );
      factCount += 1;
    }
  }
}

const out = join(here, "edgar-seed.sql");
writeFileSync(out, lines.join("\n") + "\n");
console.log(
  `Wrote ${out}: ${companies.length} companies, ${periodCount} annual periods, ` +
    `${quarterCount} quarterly periods, ${factCount} facts.`,
);
