/**
 * Generates glove-seed.sql from fundamentals.json (P026 Phase 1).
 *
 * Emits, idempotently (INSERT OR REPLACE):
 *   - the rubber-gloves industry + 7 Malaysian glove companies,
 *   - one source row per company (kind='glove-tracker', Bursa-PDF provenance),
 *   - QUARTERLY financial_period + financial_fact rows straight from the
 *     source rows (labels like "Q2 FY26" preserved),
 *   - ANNUAL periods aggregated from quarters, only for fiscal years where
 *     all 4 quarters exist (flow concepts sum; no balance-sheet data exists).
 *
 * Concept mapping (facts are positive magnitudes):
 *   revenue_mil            -> Revenue
 *   revenue - gross_profit -> CostOfRevenue (only when both present)
 *   operating_profit_mil   -> OperatingIncome
 *   net_profit_mil         -> NetIncome
 *
 * Deterministic period ids far above the AI-infra seed range (which ends
 * near 1003): quarters start at 20000 (companyIndex*1000 + i), annuals at
 * 50000 (companyIndex*1000 + fyIndex).
 *
 * Run:
 *   node seed/glove/generate.mjs
 *   wrangler d1 execute atlas-db --local --file=seed/glove/glove-seed.sql
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { GLOVE_COMPANIES, GLOVE_INDUSTRY } from "./companies.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const { rows } = JSON.parse(readFileSync(join(here, "fundamentals.json"), "utf8"));

const q = (s) =>
  s === null || s === undefined ? "NULL" : `'${String(s).replace(/'/g, "''")}'`;
const n = (v) => (v === null || v === undefined ? "NULL" : String(v));

/** "Q2 FY26" -> { fq: 2, fy: 2026 } (labels are per-company fiscal calendars). */
function parseQuarter(label) {
  const m = /^Q([1-4])\s+FY(\d{2})$/.exec(label ?? "");
  if (!m) return null;
  return { fq: Number(m[1]), fy: 2000 + Number(m[2]) };
}

function factsOf(r) {
  const facts = {};
  if (typeof r.revenue_mil === "number") facts.Revenue = r.revenue_mil;
  if (typeof r.revenue_mil === "number" && typeof r.gross_profit_mil === "number") {
    facts.CostOfRevenue = Number((r.revenue_mil - r.gross_profit_mil).toFixed(3));
  }
  if (typeof r.operating_profit_mil === "number")
    facts.OperatingIncome = r.operating_profit_mil;
  if (typeof r.net_profit_mil === "number") facts.NetIncome = r.net_profit_mil;
  return facts;
}

const lines = [];
lines.push("-- Generated by seed/glove/generate.mjs — do not edit by hand.");
lines.push("PRAGMA foreign_keys = ON;");
lines.push(
  `INSERT OR REPLACE INTO industry (id, name, sector, description) VALUES (` +
    [q(GLOVE_INDUSTRY.id), q(GLOVE_INDUSTRY.name), q(GLOVE_INDUSTRY.sector), q(GLOVE_INDUSTRY.description)].join(", ") +
    `);`,
);

let quarterCount = 0;
let annualCount = 0;
let factCount = 0;

GLOVE_COMPANIES.forEach((c, ci) => {
  const mine = rows
    .filter((r) => r.stock_code === c.code && parseQuarter(r.quarter))
    .sort((a, b) => (a.period_end < b.period_end ? -1 : 1));
  if (mine.length === 0) return;

  const latest = mine[mine.length - 1];
  const sourceId = `glove-tracker-${c.id}`;
  lines.push(
    `INSERT OR REPLACE INTO source (id, kind, name, url, retrieved_at, note) VALUES (` +
      [
        q(sourceId),
        q("glove-tracker"),
        q(`glove-tracker import — ${c.name} Bursa quarterly reports`),
        q(latest.source_url ?? "https://www.bursamalaysia.com"),
        q((latest.retrieved_at ?? "").slice(0, 10) || "2026-04-20"),
        q(
          "Imported from weisiang329-eng/glove-tracker (data/fund.json, is_mock=0 rows only). Original source: Bursa Malaysia quarterly report PDFs, auto-parsed. See apps/api/seed/glove/fundamentals.json for per-row provenance.",
        ),
      ].join(", ") +
      `);`,
  );
  lines.push(
    `INSERT OR REPLACE INTO company (id, name, ticker, exchange, segment, country, industry_id, description, reporting_currency) VALUES (` +
      [
        q(c.id), q(c.name), q(c.ticker), q(c.exchange), q(c.segment), q(c.country),
        q(GLOVE_INDUSTRY.id), q(c.description), q("MYR"),
      ].join(", ") +
      `);`,
  );

  // Quarterly periods + facts, straight from source rows.
  const byFY = new Map();
  mine.forEach((r, i) => {
    const pq = parseQuarter(r.quarter);
    const periodId = 20000 + ci * 1000 + i;
    lines.push(
      `INSERT OR REPLACE INTO financial_period (id, company_id, period_label, period_type, fiscal_year, fiscal_quarter, currency, unit, report_date, source_id) VALUES (` +
        [
          n(periodId), q(c.id), q(r.quarter), q("quarter"), n(pq.fy), n(pq.fq),
          q("MYR"), q("MYR millions"), q(r.period_end), q(sourceId),
        ].join(", ") +
        `);`,
    );
    const facts = factsOf(r);
    const factRows = Object.entries(facts).map(
      ([concept, value]) => `(${n(periodId)}, ${q(concept)}, ${n(value)}, ${q(sourceId)})`,
    );
    if (factRows.length) {
      lines.push(
        `INSERT OR REPLACE INTO financial_fact (period_id, concept, value, source_id) VALUES\n  ` +
          factRows.join(",\n  ") + `;`,
      );
      factCount += factRows.length;
    }
    quarterCount += 1;

    const fyGroup = byFY.get(pq.fy) ?? [];
    fyGroup.push({ r, facts });
    byFY.set(pq.fy, fyGroup);
  });

  // Annual aggregation — only complete fiscal years (4 distinct quarters).
  let fyIndex = 0;
  for (const [fy, group] of [...byFY.entries()].sort((a, b) => a[0] - b[0])) {
    const quarters = new Set(group.map((g) => parseQuarter(g.r.quarter).fq));
    if (quarters.size !== 4 || group.length !== 4) continue;
    const sum = {};
    for (const concept of ["Revenue", "CostOfRevenue", "OperatingIncome", "NetIncome"]) {
      if (group.every((g) => typeof g.facts[concept] === "number")) {
        sum[concept] = Number(
          group.reduce((a, g) => a + g.facts[concept], 0).toFixed(3),
        );
      }
    }
    if (Object.keys(sum).length === 0) continue;
    const periodId = 50000 + ci * 1000 + fyIndex++;
    const label = `FY${String(fy).slice(2)}`;
    const lastEnd = group.map((g) => g.r.period_end).sort().at(-1);
    lines.push(
      `INSERT OR REPLACE INTO financial_period (id, company_id, period_label, period_type, fiscal_year, fiscal_quarter, currency, unit, report_date, source_id) VALUES (` +
        [
          n(periodId), q(c.id), q(label), q("annual"), n(fy), "NULL",
          q("MYR"), q("MYR millions"), q(lastEnd), q(sourceId),
        ].join(", ") +
        `);`,
    );
    const factRows = Object.entries(sum).map(
      ([concept, value]) => `(${n(periodId)}, ${q(concept)}, ${n(value)}, ${q(sourceId)})`,
    );
    lines.push(
      `INSERT OR REPLACE INTO financial_fact (period_id, concept, value, source_id) VALUES\n  ` +
        factRows.join(",\n  ") + `;`,
    );
    factCount += factRows.length;
    annualCount += 1;
  }
});

const out = join(here, "glove-seed.sql");
writeFileSync(out, lines.join("\n") + "\n");
console.log(
  `Wrote ${out}: ${GLOVE_COMPANIES.length} companies, ${quarterCount} quarterly periods, ${annualCount} annual periods, ${factCount} facts.`,
);
