/**
 * Generates industry-metrics.sql from industry-metrics.json (P026 Phase 2).
 *
 * Attaches the MARGMA glove ASP + NBR latex cost series to the rubber-gloves
 * industry, each point carrying its own note; one source row records the
 * glove-tracker provenance. Idempotent (INSERT OR REPLACE on the
 * industry/metric/date unique key).
 *
 *   node seed/glove/generate-metrics.mjs
 *   wrangler d1 execute atlas-db --local --file=seed/glove/industry-metrics.sql
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const { provenance, series } = JSON.parse(
  readFileSync(join(here, "industry-metrics.json"), "utf8"),
);

const INDUSTRY_ID = "rubber-gloves";
const SOURCE_ID = "glove-tracker-industry";

const q = (s) =>
  s === null || s === undefined ? "NULL" : `'${String(s).replace(/'/g, "''")}'`;
const n = (v) => (v === null || v === undefined ? "NULL" : String(v));

const lines = [];
lines.push("-- Generated by seed/glove/generate-metrics.mjs — do not edit by hand.");
lines.push("PRAGMA foreign_keys = ON;");
lines.push(
  `INSERT OR REPLACE INTO source (id, kind, name, url, retrieved_at, note) VALUES (` +
    [
      q(SOURCE_ID),
      q("glove-tracker"),
      q("glove-tracker industry benchmarks (MARGMA ASP, NBR latex)"),
      q("https://margma.com.my/"),
      q("2026-04-20"),
      q(provenance),
    ].join(", ") +
    `);`,
);

let points = 0;
for (const s of series) {
  for (const p of s.points) {
    lines.push(
      `INSERT OR REPLACE INTO industry_metric (industry_id, metric_key, label, kind, observation_date, value, unit, note, source_id) VALUES (` +
        [
          q(INDUSTRY_ID), q(s.metricKey), q(s.label), q(s.kind),
          q(p.date), n(p.value), q(p.unit), q(p.note), q(SOURCE_ID),
        ].join(", ") +
        `);`,
    );
    points += 1;
  }
}

const out = join(here, "industry-metrics.sql");
writeFileSync(out, lines.join("\n") + "\n");
console.log(`Wrote ${out}: ${series.length} series, ${points} points.`);
