/**
 * Generates graph-seed.sql from relationships.mjs (P007 v1). Idempotent
 * (INSERT OR REPLACE on the from/to/type unique key); one source row records
 * the industry-structure provenance.
 *
 *   node seed/graph/generate.mjs
 *   wrangler d1 execute atlas-db --local --file=seed/graph/graph-seed.sql
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { RELATIONSHIPS } from "./relationships.mjs";

const q = (s) =>
  s === null || s === undefined ? "NULL" : `'${String(s).replace(/'/g, "''")}'`;

const SOURCE_ID = "graph-industry-structure";
const lines = [];
lines.push("-- Generated by seed/graph/generate.mjs — do not edit by hand.");
lines.push("PRAGMA foreign_keys = ON;");
lines.push(
  `INSERT OR REPLACE INTO source (id, kind, name, url, retrieved_at, note) VALUES (` +
    [
      q(SOURCE_ID),
      q("manual"),
      q("Publicly-known industry structure (supply chain + competition)"),
      q(null),
      q("2026-07-21"),
      q("Supply-chain and competitive edges between covered companies, from public company disclosures and industry reporting. Edges only between companies Atlas covers."),
    ].join(", ") +
    `);`,
);

for (const r of RELATIONSHIPS) {
  lines.push(
    `INSERT OR REPLACE INTO relationship (from_id, to_id, relation_type, label, note, source_id) VALUES (` +
      [q(r.from), q(r.to), q(r.type), q(r.label), q(r.note), q(SOURCE_ID)].join(", ") +
      `);`,
  );
}

const out = join(dirname(fileURLToPath(import.meta.url)), "graph-seed.sql");
writeFileSync(out, lines.join("\n") + "\n");
console.log(`Wrote ${out}: ${RELATIONSHIPS.length} relationships.`);
