/**
 * Generates seed.sql from data.mjs.
 *
 * Idempotent: INSERT OR REPLACE keyed on primary keys / unique indexes, so the
 * seed can be re-applied safely (it upserts). Periods get deterministic ids
 * (companyIndex*100 + periodIndex) so facts can reference them without
 * queries. Run:
 *
 *   node seed/generate.mjs                # writes seed/seed.sql
 *   wrangler d1 execute atlas-db --local --file=seed/seed.sql
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { COMPANIES, INDUSTRIES } from "./data.mjs";

const q = (s) =>
  s === null || s === undefined ? "NULL" : `'${String(s).replace(/'/g, "''")}'`;
const n = (v) => (v === null || v === undefined ? "NULL" : String(v));

const lines = [];
lines.push("-- Generated by seed/generate.mjs — do not edit by hand.");
lines.push("PRAGMA foreign_keys = ON;");

// Source rows: one per company, marking manual-seed provenance.
const SEED_NOTE =
  "Approximate annual figures compiled manually from public filings (10-K/20-F/annual reports). Not audited copies; some concepts omitted. Superseded by automated ingestion (P022).";
for (const c of COMPANIES) {
  lines.push(
    `INSERT OR REPLACE INTO source (id, kind, name, url, retrieved_at, note) VALUES (` +
      [
        q(`seed-${c.id}`),
        q("seed"),
        q(`Manual seed — ${c.name} public filings`),
        q(c.website),
        q("2026-07-21"),
        q(SEED_NOTE),
      ].join(", ") +
      `);`,
  );
}

for (const i of INDUSTRIES) {
  lines.push(
    `INSERT OR REPLACE INTO industry (id, name, sector, description) VALUES (` +
      [q(i.id), q(i.name), q(i.sector), q(i.description)].join(", ") +
      `);`,
  );
}

COMPANIES.forEach((c, ci) => {
  lines.push(
    `INSERT OR REPLACE INTO company (id, name, ticker, exchange, segment, country, industry_id, description, headquarters, founded_year, website, reporting_currency) VALUES (` +
      [
        q(c.id), q(c.name), q(c.ticker), q(c.exchange), q(c.segment), q(c.country),
        q(c.industryId), q(c.description), q(c.headquarters), n(c.foundedYear),
        q(c.website), q(c.currency),
      ].join(", ") +
      `);`,
  );

  c.periods.forEach((p, pi) => {
    const periodId = (ci + 1) * 100 + pi;
    lines.push(
      `INSERT OR REPLACE INTO financial_period (id, company_id, period_label, period_type, fiscal_year, fiscal_quarter, currency, unit, source_id) VALUES (` +
        [
          n(periodId), q(c.id), q(p.label), q("annual"), n(p.fiscalYear),
          "NULL", q(c.currency), q(c.unit), q(`seed-${c.id}`),
        ].join(", ") +
        `);`,
    );
    const factRows = Object.entries(p.facts).map(
      ([concept, value]) =>
        `(${n(periodId)}, ${q(concept)}, ${n(value)}, ${q(`seed-${c.id}`)})`,
    );
    if (factRows.length > 0) {
      lines.push(
        `INSERT OR REPLACE INTO financial_fact (period_id, concept, value, source_id) VALUES\n  ` +
          factRows.join(",\n  ") +
          `;`,
      );
    }
  });
});

const out = join(dirname(fileURLToPath(import.meta.url)), "seed.sql");
writeFileSync(out, lines.join("\n") + "\n");
console.log(
  `Wrote ${out}: ${COMPANIES.length} companies, ` +
    `${COMPANIES.reduce((a, c) => a + c.periods.length, 0)} periods, ` +
    `${COMPANIES.reduce((a, c) => a + c.periods.reduce((b, p) => b + Object.keys(p.facts).length, 0), 0)} facts.`,
);
