/**
 * Shared Postgres SQL emit helpers for the seed generators.
 *
 * All seeds are idempotent upserts (INSERT ... ON CONFLICT ... DO UPDATE) keyed
 * on natural keys, so they can be re-applied safely. Financial facts are
 * inserted by looking up their period's serial id via its natural key
 * (company_id, period_label) — no hard-coded ids — which keeps the serial
 * sequence consistent across all seed files.
 */
export const q = (s) =>
  s === null || s === undefined ? "NULL" : `'${String(s).replace(/'/g, "''")}'`;

export const n = (v) => (v === null || v === undefined ? "NULL" : String(v));

/**
 * Emit an upsert. `cols` is an ordered object { column: sqlLiteral }. `conflict`
 * is the conflict-target column list. `update` lists columns to overwrite on
 * conflict (empty → DO NOTHING).
 */
export function upsert(table, cols, conflict, update) {
  const names = Object.keys(cols);
  const vals = Object.values(cols);
  const action =
    update && update.length
      ? `DO UPDATE SET ${update.map((c) => `${c} = EXCLUDED.${c}`).join(", ")}`
      : "DO NOTHING";
  return (
    `INSERT INTO ${table} (${names.join(", ")}) VALUES (${vals.join(", ")}) ` +
    `ON CONFLICT (${conflict.join(", ")}) ${action};`
  );
}

/**
 * Upsert a financial_period by its natural key (company_id, period_label).
 * `p` carries the column literals already quoted/numified.
 */
export function upsertPeriod(p) {
  return upsert(
    "financial_period",
    {
      company_id: q(p.companyId),
      period_label: q(p.periodLabel),
      period_type: q(p.periodType),
      fiscal_year: n(p.fiscalYear),
      fiscal_quarter: n(p.fiscalQuarter),
      currency: q(p.currency),
      unit: q(p.unit),
      report_date: q(p.reportDate ?? null),
      source_id: q(p.sourceId),
    },
    ["company_id", "period_label"],
    ["period_type", "fiscal_year", "fiscal_quarter", "currency", "unit", "report_date", "source_id"],
  );
}

/**
 * Upsert all facts for one period in a single statement: resolve the period's
 * serial id from its natural key, cross-join a VALUES list of (concept, value),
 * and upsert. `facts` is { concept: value }; null/undefined values are skipped.
 */
export function upsertFacts(companyId, periodLabel, facts, sourceId) {
  const rows = Object.entries(facts).filter(
    ([, v]) => v !== null && v !== undefined && Number.isFinite(v),
  );
  if (rows.length === 0) return null;
  const values = rows
    .map(([concept, value]) => `(${q(concept)}, ${n(value)}::double precision)`)
    .join(", ");
  return (
    `INSERT INTO financial_fact (period_id, concept, value, source_id)\n` +
    `SELECT p.id, v.concept, v.value, ${q(sourceId)}\n` +
    `FROM financial_period p\n` +
    `JOIN (VALUES ${values}) AS v(concept, value) ON true\n` +
    `WHERE p.company_id = ${q(companyId)} AND p.period_label = ${q(periodLabel)}\n` +
    `ON CONFLICT (period_id, concept) DO UPDATE SET value = EXCLUDED.value, source_id = EXCLUDED.source_id;`
  );
}

export const HEADER = (name) =>
  `-- Generated by ${name} — do not edit by hand. Postgres (Supabase).`;
